<?php

namespace App\Commands;

use App\Models\AssetItemModel;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\Database;

class BackfillAssetItems extends BaseCommand
{
    protected $group       = 'Inventory';
    protected $name        = 'assets:backfill-items';
    protected $description = 'Backfill item-level records from existing lab_assets stock data.';
    protected $usage       = 'assets:backfill-items [options]';
    protected $arguments   = [];
    protected $options     = [
        '--dry-run' => 'Simulate insert/update without writing data.',
        '--asset'   => 'Backfill only one asset_id (integer).',
        '--limit'   => 'Limit number of master assets processed.',
    ];

    public function run(array $params): void
    {
        $opts      = $this->normalizeOptions();
        $isDryRun  = isset($opts['dry-run']);
        $assetId   = isset($opts['asset']) ? (int) $opts['asset'] : null;
        $limit     = isset($opts['limit']) ? max(1, (int) $opts['limit']) : null;
        $db        = Database::connect();
        $assetItem = new AssetItemModel();

        $assetQuery = $db->table('lab_assets')
            ->select('id, asset_code, lab_id, condition_status, stock_total, stock_available')
            ->where('asset_type', 'equipment')
            ->orderBy('id', 'ASC');

        if ($assetId !== null && $assetId > 0) {
            $assetQuery->where('id', $assetId);
        }

        if ($limit !== null) {
            $assetQuery->limit($limit);
        }

        $assets = $assetQuery->get()->getResultArray();

        if (empty($assets)) {
            CLI::write('No matching assets found.', 'yellow');
            return;
        }

        CLI::write('Backfill mode: ' . ($isDryRun ? 'DRY RUN' : 'WRITE'), 'yellow');
        CLI::write('Assets to process: ' . count($assets));

        $summary = [
            'assets'         => 0,
            'items_created'  => 0,
            'assets_skipped' => 0,
            'assets_updated' => 0,
        ];

        foreach ($assets as $asset) {
            $summary['assets']++;

            $currentAssetId = (int) ($asset['id'] ?? 0);
            $targetTotal    = max(0, (int) ($asset['stock_total'] ?? 0));
            $targetAvail    = max(0, (int) ($asset['stock_available'] ?? 0));
            $targetAvail    = min($targetAvail, $targetTotal);

            $existingTotal = (int) $db->table('asset_items')
                ->where('asset_id', $currentAssetId)
                ->countAllResults();

            $existingActive = (int) $db->table('asset_items')
                ->where('asset_id', $currentAssetId)
                ->where('inventory_status', 'aktif')
                ->countAllResults();

            $missingItems = max(0, $targetTotal - $existingTotal);
            $activeNeeded = max(0, $targetAvail - $existingActive);

            if ($missingItems === 0) {
                $summary['assets_skipped']++;
                $this->recomputeMasterAggregate($db, $currentAssetId, $isDryRun, $summary);
                CLI::write(sprintf('Asset #%d skip (existing=%d, target=%d)', $currentAssetId, $existingTotal, $targetTotal), 'cyan');
                continue;
            }

            CLI::write(sprintf('Asset #%d create %d item(s)', $currentAssetId, $missingItems), 'green');

            for ($i = 1; $i <= $missingItems; $i++) {
                $sequence  = $existingTotal + $i;
                $itemCode  = $this->generateUniqueItemCode($db, (string) ($asset['asset_code'] ?? ''), $currentAssetId, $sequence);
                $itemState = $i <= $activeNeeded ? 'aktif' : 'dipinjam';

                $payload = [
                    'asset_id'          => $currentAssetId,
                    'item_code'         => $itemCode,
                    'serial_number'     => null,
                    'lab_id'            => $asset['lab_id'] ?? null,
                    'location_detail'   => null,
                    'condition_status'  => $this->normalizeCondition((string) ($asset['condition_status'] ?? 'baik')),
                    'inventory_status'  => $itemState,
                    'is_loanable'       => $itemState === 'aktif' ? 1 : 0,
                    'acquisition_date'  => null,
                    'warranty_until'    => null,
                    'notes'             => 'Generated by assets:backfill-items command',
                    'responsible_user_id' => null,
                    'created_by'        => null,
                    'updated_by'        => null,
                ];

                if ($isDryRun) {
                    continue;
                }

                $assetItem->insert($payload);
                $summary['items_created']++;
            }

            $this->recomputeMasterAggregate($db, $currentAssetId, $isDryRun, $summary);
        }

        CLI::newLine();
        CLI::write('Backfill summary', 'yellow');
        CLI::write('Assets processed : ' . $summary['assets']);
        CLI::write('Assets skipped   : ' . $summary['assets_skipped']);
        CLI::write('Items created    : ' . $summary['items_created']);
        CLI::write('Assets updated   : ' . $summary['assets_updated']);
    }

    private function recomputeMasterAggregate($db, int $assetId, bool $isDryRun, array &$summary): void
    {
        $total = (int) $db->table('asset_items')
            ->where('asset_id', $assetId)
            ->countAllResults();

        $available = (int) $db->table('asset_items')
            ->where('asset_id', $assetId)
            ->where('inventory_status', 'aktif')
            ->where('is_loanable', 1)
            ->countAllResults();

        $inventoryStatus = $total <= 0 ? 'hilang' : ($available > 0 ? 'aktif' : 'dipinjam');

        if (! $isDryRun) {
            $db->table('lab_assets')
                ->where('id', $assetId)
                ->update([
                    'stock_total'     => $total,
                    'stock_available' => $available,
                    'inventory_status'=> $inventoryStatus,
                ]);
            $summary['assets_updated']++;
        }
    }

    private function generateUniqueItemCode($db, string $assetCode, int $assetId, int $sequence): string
    {
        $baseCode = trim($assetCode) !== ''
            ? trim($assetCode)
            : ('AST-' . str_pad((string) $assetId, 4, '0', STR_PAD_LEFT));

        $candidate = $baseCode . '-' . str_pad((string) $sequence, 4, '0', STR_PAD_LEFT);
        $suffix    = 1;

        while ($db->table('asset_items')->where('item_code', $candidate)->countAllResults() > 0) {
            $candidate = $baseCode . '-' . str_pad((string) $sequence, 4, '0', STR_PAD_LEFT) . '-' . $suffix;
            $suffix++;
        }

        return $candidate;
    }

    private function normalizeCondition(string $condition): string
    {
        $value = strtolower(trim($condition));
        $valid = ['baik', 'perlu_perbaikan', 'rusak', 'rusak_ringan', 'rusak_berat'];

        if (in_array($value, $valid, true)) {
            return $value;
        }

        return 'baik';
    }

    /**
     * @return array<string, string|true>
     */
    private function normalizeOptions(): array
    {
        $result = [];

        foreach (CLI::getOptions() as $rawKey => $rawVal) {
            if (str_contains($rawKey, '=')) {
                [$k, $v] = explode('=', $rawKey, 2);
                $result[$k] = $v;
                continue;
            }

            $result[$rawKey] = ($rawVal === null) ? true : $rawVal;
        }

        return $result;
    }
}
